version: '3.9'

volumes:
  pgdata:
  shell_history:
  ipy_history:

services:
  nginx-proxy:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf

  adminer:
    image: adminer:latest
    profiles: ["debug"]
    restart: always
    ports:
        - 8000:8000

  db:
    image: postgres:13-alpine
    volumes:
      - pgdata:/var/lib/postgresql/data/
      - ./scripts/db/:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=$DJANGO_POSTGRES_PASSWORD

  wdb:
    image: kozea/wdb
    profiles: ["debug"]
    ports:
      - "1984:1984"

  filmer:
    build:
      context: .
      target: prod
    command: python manage.py runserver 0.0.0.0:8000
    # user: "1000:1000"
    volumes:
      - .:/code
      - shell_history:/root/hist
      - ipy_history:/root/.ipython/profile_default
    expose:
      - 81
      - 80
    links:
      - db
    env_file:
      - .env
