# Generated by Django 3.2.6 on 2021-08-19 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MovieCast",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("actor_name", models.CharField(max_length=100)),
                ("role", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=128)),
                ("imdb_id", models.CharField(max_length=10)),
                ("year", models.PositiveSmallIntegerField()),
                ("data", models.JSONField(default=dict)),
                ("poster", models.URLField()),
                ("cast", models.ManyToManyField(related_name="movies", to="api.MovieCast")),
            ],
        ),
    ]
