name: Django CI

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      DATABASE_URL: postgres://postgres:postgres@127.0.0.1:5432/github_actions
      DJANGO_SECRET_KEY: iy78m@(4lt+ad!ntn6u3v!9oly(pd$e$vch85suqs2_yl17cm2

    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]
        poetry-version: [1.1.8]


    steps:
    - name: Checkout code # checking our the code at current commit that triggers the workflow
      uses: actions/checkout@v2.3.4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run image
      uses: abatilo/actions-poetry@v2.1.2
      with:
        poetry-version: ${{ matrix.poetry-version }}

    - name: Install dependencies
      run: poetry install

    - name: Run Django Check
      run: poetry run python manage.py check

    - name: Run Django Check
      run: poetry run pytest
